#!/usr/bin/env python3
"""
Week 04 structural checker - Modeling the System with UML.

DO NOT EDIT THIS FILE. The grader re-runs the original.

Run it from inside your week-04 folder:

    python tests/check_models.py            # for you
    python tests/check_models.py --json     # for the grading pipeline

It checks SHAPE, never QUALITY: that the files exist, that the required elements are there, that
the rules from the handout are visible in the diagrams and that the worksheet is filled in. A
diagram can pass every check here and still be a poor model. Your review in lab-report.md is what
gets graded; this only tells you what is missing.

Verdicts:
  PASS   the check is satisfied
  FAIL   the file is there and readable, but the check is not satisfied
  ERROR  the file this check needs is missing or unreadable, so the check could not run

Exit codes: 0 = no FAIL and no ERROR · 1 = at least one FAIL or ERROR · 2 = wrong working directory.

Python 3.8+, standard library only.
"""

import argparse
import json
import os
import re
import sys

RESULTS = []

TITLES = {
    "UC1": "Use case: both actors declared", "UC2": "Use case: named system boundary",
    "UC3": "Use case: actors outside the boundary", "UC4": "Use case: every scenario goal present",
    "UC5": "Use case: no actor linked to a confirmation", "UC6": "Use case: actor responsibilities",
    "UC7": "Use case: goals, not screens or components", "UC8": "Use case: include/extend justified",
    "UC9": "Use case: revised, not the original",
    "CL1": "Class: Student, Room, Booking", "CL2": "Class: Booking associated with both",
    "CL3": "Class: multiplicity at both ends", "CL4": "Class: 1 to 0..* multiplicities",
    "CL5": "Class: inheritance/composition justified", "CL6": "Class: domain concepts only",
    "CL7": "Class: attributes R1-R3 need", "CL8": "Class: R2 stated in a note",
    "SQ1": "Sequence: three lifelines", "SQ2": "Sequence: guarded alt",
    "SQ3": "Sequence: validation before creation", "SQ4": "Sequence: nothing saved on failure",
    "SQ5": "Sequence: every message labelled", "SQ6": "Sequence: R1 visible", "SQ7": "Sequence: R3 visible",
    "AC1": "Activity: initial and final nodes", "AC2": "Activity: one decision per rule",
    "AC3": "Activity: labelled guards", "AC4": "Activity: no parallel paths",
    "AC5": "Activity: confirmation and rejection", "AC6": "Activity: create after the last check",
    "BH0": "Behaviour diagram present",
    "FI1": "Files: AI originals kept", "FI2": "Files: rendered images",
    "LR1": "Worksheet §1 setup", "LR2": "Worksheet §2 prompts", "LR3": "Worksheet §3 use-case findings",
    "LR4": "Worksheet §4 relationships and assumptions", "LR5": "Worksheet §5 behaviour findings",
    "LR6": "Worksheet §6 critique verdicts", "LR7": "Worksheet §8 change log",
    "CS1": "Consistency: approved stories", "CS2": "Consistency: R1-R4 traced",
    "CS3": "Consistency: every use case traced", "CS4": "Consistency: lifelines explained",
}


def record(check_id, verdict, message):
    RESULTS.append((check_id, verdict, message))


def norm(text):
    """Lowercase and strip everything that is not a letter or a digit."""
    return re.sub(r"[^a-z0-9]", "", (text or "").lower())


def read(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except (OSError, UnicodeDecodeError):
        return None


# ----------------------------------------------------------------------------------------------
# PlantUML helpers
# ----------------------------------------------------------------------------------------------

def puml_body(src):
    """Return (lines, raw_lines). lines have comments and block comments blanked out but keep
    their index, so raw_lines[i] can be inspected for the '  why:' comment above line i."""
    raw = src.splitlines()
    out = []
    in_block = False
    for line in raw:
        s = line
        if in_block:
            if "'/" in s:
                s = s.split("'/", 1)[1]
                in_block = False
            else:
                out.append("")
                continue
        if "/'" in s:
            before, after = s.split("/'", 1)
            if "'/" in after:
                s = before + after.split("'/", 1)[1]
            else:
                s = before
                in_block = True
        if s.strip().startswith("'"):
            s = ""
        out.append(s)
    return out, raw


def has_start_end(src):
    return "@startuml" in src and "@enduml" in src


def justified(raw_lines, idx):
    """True if the nearest non-empty line above idx is a comment containing 'why:'."""
    j = idx - 1
    while j >= 0 and not raw_lines[j].strip():
        j -= 1
    return j >= 0 and raw_lines[j].strip().startswith("'") and "why:" in raw_lines[j].lower()


ENDPOINT = r'(\([^)]*\)|:[^:]+:|"[^"]+"|[A-Za-z_][\w.]*)'
UC_ARROW = r'(<\|?|\*|o)?([-.]+)(?:(?:left|right|up|down|le|ri|l|r|u|d)[-.]*)?(\|?>|\*|o)?'


# ----------------------------------------------------------------------------------------------
# Use-case diagram
# ----------------------------------------------------------------------------------------------

def parse_usecase(src):
    lines, raw = puml_body(src)
    actors = {}        # key -> display name
    usecases = {}      # key -> display name
    boundary_names = []
    actors_inside = []
    links = []         # (a_key, b_key, arrow, label, line_index)
    depth = 0
    boundary_depths = []

    def add_uc(name, alias=None):
        key = alias or name
        usecases[key] = name
        usecases.setdefault(name, name)
        return key

    def resolve(ep):
        ep = ep.strip()
        if ep.startswith("(") and ep.endswith(")"):
            name = ep[1:-1].strip()
            if name not in usecases:
                add_uc(name)
            return name, "uc"
        if ep.startswith(":") and ep.endswith(":"):
            name = ep[1:-1].strip()
            actors.setdefault(name, name)
            return name, "actor"
        if ep.startswith('"') and ep.endswith('"'):
            ep = ep[1:-1]
        if ep in actors:
            return ep, "actor"
        if ep in usecases:
            return ep, "uc"
        return ep, "unknown"

    for i, line in enumerate(lines):
        s = line.strip()
        if not s:
            continue
        m = re.match(r'^(rectangle|package|frame|node|folder)\s+(?:"([^"]+)"|([\w.]+))?[^{]*\{', s)
        if m:
            name = m.group(2) or m.group(3) or ""
            boundary_names.append(name)
            boundary_depths.append(depth + 1)
        opens = s.count("{")
        closes = s.count("}")
        inside = bool(boundary_depths) and depth >= boundary_depths[0]

        m = re.match(r'^actor\s+(?:"([^"]+)"|:([^:]+):|([\w.]+))(?:\s+as\s+(?:"([^"]+)"|([\w.]+)))?', s)
        if m:
            name = m.group(1) or m.group(2) or m.group(3)
            alias = m.group(5) or (m.group(3) if m.group(4) else None)
            display = m.group(4) or name
            if m.group(4):          # actor Alias as "Display"
                actors[m.group(3) or name] = display
            else:
                actors[alias or name] = name
                actors.setdefault(name, name)
            if inside:
                actors_inside.append(display)
            depth += opens - closes
            continue

        m = re.match(r'^usecase\s+(?:"([^"]+)"|\(([^)]+)\)|([\w.]+))(?:\s+as\s+(?:"([^"]+)"|([\w.]+)))?', s)
        if m:
            name = m.group(1) or m.group(2) or m.group(3)
            if m.group(4):          # usecase UC1 as "Book room"
                add_uc(m.group(4), m.group(3) or name)
            else:
                add_uc(name, m.group(5))
            depth += opens - closes
            continue

        m = re.match(r'^\(([^)]+)\)\s+as\s+([\w.]+)', s)
        if m:
            add_uc(m.group(1).strip(), m.group(2))
            depth += opens - closes
            continue

        m = re.match(r'^' + ENDPOINT + r'\s*' + UC_ARROW + r'\s*' + ENDPOINT + r'\s*(?::\s*(.*))?$', s)
        if m and ("-" in (m.group(3) or "") or "." in (m.group(3) or "")):
            a, at = resolve(m.group(1))
            b, bt = resolve(m.group(5))
            arrow = (m.group(2) or "") + (m.group(3) or "") + (m.group(4) or "")
            links.append((a, at, b, bt, arrow, (m.group(6) or ""), i))
        depth += opens - closes

    return {
        "actors": actors,
        "usecases": usecases,
        "boundaries": boundary_names,
        "actors_inside": actors_inside,
        "links": links,
        "lines": lines,
        "raw": raw,
    }


REQUIRED_UC = [
    ("View availability", lambda n: "availab" in n),
    ("Book room", lambda n: "book" in n and "cancel" not in n and "block" not in n),
    ("Cancel booking", lambda n: "cancel" in n),
    ("Block / unblock room", lambda n: "block" in n),
    ("Review usage", lambda n: "usage" in n),
]


def uc_display_names(uc):
    names = set(uc["usecases"].values())
    return sorted(names)


def check_usecase(path, orig_path):
    src = read(path)
    if src is None:
        for cid in ("UC1", "UC2", "UC3", "UC4", "UC5", "UC6", "UC7", "UC8", "UC9"):
            record(cid, "ERROR", "models/use-case.puml not found")
        return None
    if not has_start_end(src):
        for cid in ("UC1", "UC2", "UC3", "UC4", "UC5", "UC6", "UC7", "UC8", "UC9"):
            record(cid, "ERROR", "models/use-case.puml has no @startuml / @enduml")
        return None

    uc = parse_usecase(src)
    actor_names = {norm(v) for v in uc["actors"].values()} | {norm(k) for k in uc["actors"]}

    missing = [a for a in ("student", "administrator") if a not in actor_names]
    record("UC1", "FAIL" if missing else "PASS",
           "missing actor(s): " + ", ".join(missing) if missing else "Student and Administrator declared")

    named = [b for b in uc["boundaries"] if b.strip()]
    record("UC2", "PASS" if named else "FAIL",
           'named system boundary: "%s"' % named[0] if named
           else 'no named boundary - use: rectangle "Smart Campus booking system" { ... }')

    if not named:
        record("UC3", "FAIL", "no boundary, so actors cannot be outside it")
    elif uc["actors_inside"]:
        record("UC3", "FAIL", "actor(s) declared inside the boundary: " + ", ".join(uc["actors_inside"]))
    else:
        record("UC3", "PASS", "all actors declared outside the boundary")

    names = uc_display_names(uc)
    missing_uc = [label for label, test in REQUIRED_UC if not any(test(norm(n)) for n in names)]
    record("UC4", "FAIL" if missing_uc else "PASS",
           "missing use case(s): " + ", ".join(missing_uc) if missing_uc
           else "all scenario goals present (%d use cases)" % len(names))

    def display(key):
        return uc["usecases"].get(key, uc["actors"].get(key, key))

    def is_actor(key, kind):
        return kind == "actor" or norm(key) in actor_names

    # actor <-> use case associations (include/extend/generalisation excluded)
    assoc = []
    for a, at, b, bt, arrow, label, i in uc["links"]:
        lab = label.lower()
        if "include" in lab or "extend" in lab or "|" in arrow:
            continue
        if is_actor(a, at) and not is_actor(b, bt):
            assoc.append((norm(display(a)), norm(display(b))))
        elif is_actor(b, bt) and not is_actor(a, at):
            assoc.append((norm(display(b)), norm(display(a))))

    bad_conf = [(ac, u) for ac, u in assoc if "confirm" in u]
    record("UC5", "FAIL" if bad_conf else "PASS",
           "an actor is associated with a confirmation use case (%s) - R4 is an outcome of booking, "
           "not an actor goal" % ", ".join("%s-%s" % p for p in bad_conf) if bad_conf
           else "no actor is associated with a confirmation use case")

    wrong = []
    for ac, u in assoc:
        if "admin" in ac and ("cancel" in u or ("book" in u and "block" not in u)):
            wrong.append("Administrator-" + u)
        if "student" in ac and ("block" in u or "usage" in u):
            wrong.append("Student-" + u)
    record("UC6", "FAIL" if wrong else "PASS",
           "association(s) the scenario does not give that actor: " + ", ".join(wrong) if wrong
           else "actor responsibilities match the scenario")

    forbidden = ("screen", "page", "button", "database", "table", "repository", "service", "api", "form")
    bad_names = [n for n in names if any(f in norm(n) for f in forbidden)]
    bad_actor = [a for a in uc["actors"].values() if norm(a) in ("system", "database", "smartcampus")]
    probs = bad_names + ["actor " + a for a in bad_actor]
    record("UC7", "FAIL" if probs else "PASS",
           "design/UI vocabulary where a user goal should be: " + ", ".join(probs) if probs
           else "use cases are goals, not screens or components")

    unjust = []
    for a, at, b, bt, arrow, label, i in uc["links"]:
        lab = label.lower()
        kind = "include" if "include" in lab else "extend" if "extend" in lab else "generalization" if "|" in arrow else None
        if kind and not justified(uc["raw"], i):
            unjust.append("line %d (%s)" % (i + 1, kind))
    record("UC8", "FAIL" if unjust else "PASS",
           "no ' why: comment directly above: " + ", ".join(unjust) if unjust
           else "every include / extend / generalization carries a ' why: comment (or there are none)")

    orig = read(orig_path)
    if orig is None:
        record("UC9", "ERROR", "models/original/use-case.puml not found - save the AI's first output there")
    elif norm(orig) == norm(src):
        record("UC9", "FAIL", "revised use-case.puml is identical to the original - Task 1 asks for a revised diagram")
    else:
        record("UC9", "PASS", "revised diagram differs from the AI's original")
    return uc


# ----------------------------------------------------------------------------------------------
# Class diagram
# ----------------------------------------------------------------------------------------------

CL_ARROW = r'([<*o]?\|?[-.]+(?:(?:left|right|up|down|l|r|u|d)[-.]+)?\|?[>*o]?)'


def parse_class(src):
    lines, raw = puml_body(src)
    classes = {}     # name -> list of member lines
    aliases = {}
    relations = []   # (left, lmult, arrow, rmult, right, label, idx)
    notes = []
    current = None
    in_note = False
    note_buf = []
    for i, line in enumerate(lines):
        s = line.strip()
        if in_note:
            if re.match(r'^end\s*note', s):
                notes.append(" ".join(note_buf))
                note_buf = []
                in_note = False
            else:
                note_buf.append(s)
            continue
        if not s:
            continue
        if current is not None:
            if s.startswith("}"):
                current = None
            else:
                classes[current].append(s)
            continue
        m = re.match(r'^note\b(.*)$', s)
        if m:
            rest = m.group(1)
            if ":" in rest:
                notes.append(rest.split(":", 1)[1])
            else:
                in_note = True
            continue
        m = re.match(r'^(?:abstract\s+class|abstract|class|entity|enum|interface)\s+(?:"([^"]+)"|([\w.]+))'
                     r'(?:\s+as\s+([\w.]+))?[^{]*(\{)?\s*(\})?', s)
        if m:
            name = m.group(1) or m.group(2)
            classes.setdefault(name, [])
            if m.group(3):
                aliases[m.group(3)] = name
            if m.group(4) and not m.group(5):
                current = name
            continue
        m = re.match(r'^("?[\w.]+"?)\s*(?:"([^"]*)")?\s*' + CL_ARROW + r'\s*(?:"([^"]*)")?\s*("?[\w.]+"?)\s*(?::\s*(.*))?$', s)
        if m and ("-" in m.group(3) or "." in m.group(3)):
            left = aliases.get(m.group(1).strip('"'), m.group(1).strip('"'))
            right = aliases.get(m.group(5).strip('"'), m.group(5).strip('"'))
            relations.append((left, m.group(2), m.group(3), m.group(4), right, m.group(6) or "", i))
            classes.setdefault(left, [])
            classes.setdefault(right, [])
    return {"classes": classes, "relations": relations, "notes": notes, "raw": raw}


def check_class(path):
    ids = ("CL1", "CL2", "CL3", "CL4", "CL5", "CL6", "CL7", "CL8")
    src = read(path)
    if src is None:
        for cid in ids:
            record(cid, "ERROR", "models/class.puml not found")
        return None
    if not has_start_end(src):
        for cid in ids:
            record(cid, "ERROR", "models/class.puml has no @startuml / @enduml")
        return None
    cl = parse_class(src)
    cmap = {norm(k): k for k in cl["classes"]}

    missing = [c for c in ("Student", "Room", "Booking") if norm(c) not in cmap]
    record("CL1", "FAIL" if missing else "PASS",
           "missing class(es): " + ", ".join(missing) if missing else "Student, Room and Booking present")

    def rel_between(a, b):
        out = []
        for r in cl["relations"]:
            if {norm(r[0]), norm(r[4])} == {norm(a), norm(b)}:
                out.append(r)
        return out

    sb = rel_between("Student", "Booking")
    rb = rel_between("Room", "Booking")
    miss_rel = [n for n, r in (("Student-Booking", sb), ("Room-Booking", rb)) if not r]
    record("CL2", "FAIL" if miss_rel else "PASS",
           "no association: " + ", ".join(miss_rel) if miss_rel else "Booking is associated with Student and with Room")

    no_mult = []
    for left, lm, arrow, rm, right, label, i in cl["relations"]:
        if "|" in arrow:
            continue
        if not (lm and lm.strip()) or not (rm and rm.strip()):
            no_mult.append("%s-%s" % (left, right))
    record("CL3", "FAIL" if no_mult else "PASS",
           "association(s) without a multiplicity at both ends: " + ", ".join(no_mult) if no_mult
           else "every association has multiplicities at both ends")

    bad = []
    for name, rels in (("Student", sb), ("Room", rb)):
        for left, lm, arrow, rm, right, label, i in rels:
            if norm(left) == norm(name):
                owner_m, booking_m = lm, rm
            else:
                owner_m, booking_m = rm, lm
            if (owner_m or "").strip() != "1":
                bad.append("%s end is %r, expected 1" % (name, owner_m))
            if (booking_m or "").strip() not in ("0..*", "*"):
                bad.append("Booking end (towards %s) is %r, expected 0..*" % (name, booking_m))
    if miss_rel:
        record("CL4", "FAIL", "cannot check multiplicities - association missing")
    else:
        record("CL4", "FAIL" if bad else "PASS",
               "; ".join(bad) if bad else "1 student / 1 room per booking, 0..* bookings per student and per room")

    unjust = []
    for left, lm, arrow, rm, right, label, i in cl["relations"]:
        kind = None
        if "|" in arrow:
            kind = "inheritance"
        elif "*" in arrow:
            kind = "composition"
        elif arrow.startswith("o") or arrow.endswith("o"):
            kind = "aggregation"
        if kind and not justified(cl["raw"], i):
            unjust.append("%s-%s (%s)" % (left, right, kind))
    record("CL5", "FAIL" if unjust else "PASS",
           "no ' why: comment directly above: " + ", ".join(unjust) if unjust
           else "every inheritance / composition / aggregation carries a ' why: comment (or there are none)")

    design_words = ("service", "repository", "controller", "screen", "page", "manager", "dao",
                    "form", "database", "ui", "view", "handler")
    design = [c for c in cl["classes"] if any(norm(c).endswith(w) or norm(c) == w for w in design_words)]
    record("CL6", "FAIL" if design else "PASS",
           "design or UI class(es) in a domain model: " + ", ".join(design) if design
           else "only domain concepts in the class diagram")

    probs = []
    bk = [norm(x) for x in cl["classes"].get(cmap.get("booking", ""), [])]
    rm_ = [norm(x) for x in cl["classes"].get(cmap.get("room", ""), [])]
    if not any("start" in x for x in bk):
        probs.append("Booking has no start attribute (R1)")
    if not any("end" in x or "duration" in x for x in bk):
        probs.append("Booking has no end or duration attribute (R1, R2)")
    if not any("status" in x or "state" in x or "active" in x or "cancel" in x for x in bk):
        probs.append("Booking has no status (R2 says *active* bookings)")
    if not any("block" in x for x in rm_):
        probs.append("Room has no blocked state (R3)")
    record("CL7", "FAIL" if probs else "PASS",
           "; ".join(probs) if probs else "attributes needed by R1-R3 are present")

    note_text = " ".join(cl["notes"]).lower()
    ok = "r2" in note_text or "overlap" in note_text
    record("CL8", "PASS" if ok else "FAIL",
           "a note states R2 (no overlapping active bookings)" if ok
           else "no note states R2 - multiplicity cannot show 'no overlap'; add a note on Booking")
    return cl


# ----------------------------------------------------------------------------------------------
# Sequence diagram
# ----------------------------------------------------------------------------------------------

SEQ_ARROW = r'([<xo]?<{0,2}-{1,2}>{0,2}[xo]?|[<xo]?<{0,2}-{1,2}\\{1,2}|/{1,2}-{1,2}>?)'


def parse_sequence(src):
    lines, raw = puml_body(src)
    participants = {}   # key -> display
    messages = []       # (idx, frm, to, label, branch_id)
    notes = []
    branches = []       # [guard, kind]
    stack = []
    for i, line in enumerate(lines):
        s = line.strip()
        if not s:
            continue
        m = re.match(r'^(actor|participant|boundary|control|entity|database|collections|queue)\s+'
                     r'(?:"([^"]+)"|([\w.:]+))(?:\s+as\s+([\w.]+))?', s)
        if m:
            display = m.group(2) or m.group(3)
            key = m.group(4) or display
            participants[key] = display
            participants.setdefault(display, display)
            continue
        m = re.match(r'^(alt|opt|loop|group|critical|break|par)\b\s*(.*)$', s)
        if m:
            branches.append([m.group(2), m.group(1)])
            stack.append(len(branches) - 1)
            continue
        m = re.match(r'^else\b\s*(.*)$', s)
        if m and stack:
            kind = branches[stack[-1]][1]
            branches.append([m.group(1), kind + "-else"])
            stack[-1] = len(branches) - 1
            continue
        if re.match(r'^end$', s) and stack:
            stack.pop()
            continue
        if re.match(r'^(r?h?note)\b', s):
            if ":" in s:
                notes.append(s.split(":", 1)[1])
            else:
                buf = []
                j = i + 1
                while j < len(lines) and not re.match(r'^\s*end\s*note', lines[j]):
                    buf.append(lines[j])
                    j += 1
                notes.append(" ".join(buf))
            continue
        m = re.match(r'^("[^"]+"|[\w.]+)\s*' + SEQ_ARROW + r'\s*("[^"]+"|[\w.]+)\s*(?::\s*(.*))?$', s)
        if m:
            messages.append((i, m.group(1).strip('"'), m.group(3).strip('"'), m.group(4) or "",
                             stack[-1] if stack else None))
    return {"participants": participants, "messages": messages, "notes": notes, "branches": branches}


def check_sequence(path):
    ids = ("SQ1", "SQ2", "SQ3", "SQ4", "SQ5", "SQ6", "SQ7")
    src = read(path)
    if src is None:
        for cid in ids:
            record(cid, "ERROR", "models/sequence.puml not found")
        return None
    if not has_start_end(src):
        for cid in ids:
            record(cid, "ERROR", "models/sequence.puml has no @startuml / @enduml")
        return None
    sq = parse_sequence(src)
    disp = [norm(v) for v in sq["participants"].values()]
    missing = [p for p in ("Student", "BookingService", "BookingRepository")
               if not any(norm(p) in d for d in disp)]
    record("SQ1", "FAIL" if missing else "PASS",
           "missing lifeline(s): " + ", ".join(missing) if missing
           else "Student, BookingService and BookingRepository lifelines present")

    alts = [b for b in sq["branches"] if b[1] in ("alt", "alt-else")]
    guarded = [b for b in alts if b[0].strip()]
    ok = len([b for b in alts if b[1] == "alt"]) >= 1 and len(alts) >= 2 and len(guarded) == len(alts)
    record("SQ2", "PASS" if ok else "FAIL",
           "alt block with a guard on every branch (%d branches)" % len(alts) if ok
           else "need an alt block with at least two branches, each with a guard like [created] / [unavailable]")

    create_re = re.compile(r"create|save|insert|persist|store|reserve|trycreate", re.I)
    valid_re = re.compile(r"valid|check|rule|verif", re.I)
    first_create = next((k for k, msg in enumerate(sq["messages"]) if create_re.search(msg[3])), None)
    first_valid = next((k for k, msg in enumerate(sq["messages"]) if valid_re.search(msg[3])), None)
    if first_create is None:
        record("SQ3", "FAIL", "no message creates or saves the booking")
    elif first_valid is None or first_valid > first_create:
        record("SQ3", "FAIL", "no validation message before the first create/save message")
    else:
        record("SQ3", "PASS", "validation happens before creation")

    fail_re = re.compile(r"invalid|fail|conflict|unavail|block|reject|overlap|error|not|deny|denied", re.I)
    leaks = []
    for idx, frm, to, label, b in sq["messages"]:
        if b is not None and fail_re.search(sq["branches"][b][0]) and create_re.search(label) \
                and not re.search(r"trycreate", label, re.I):
            leaks.append(label.strip())
    record("SQ4", "FAIL" if leaks else "PASS",
           "a failure branch still creates/saves: " + "; ".join(leaks) if leaks
           else "nothing is saved on a failure branch")

    unlabeled = [msg for msg in sq["messages"] if not msg[3].strip()]
    record("SQ5", "FAIL" if unlabeled else "PASS",
           "%d message(s) without a label" % len(unlabeled) if unlabeled else "every message is labelled")

    text = " ".join([m[3] for m in sq["messages"]] + [b[0] for b in sq["branches"]] + sq["notes"]).lower()
    ntext = norm(text)
    r1 = any(w in ntext for w in ("r1", "timerange", "duration", "future"))
    record("SQ6", "PASS" if r1 else "FAIL",
           "R1 (time range) is visible - checked or stated as a precondition" if r1
           else "R1 is invisible - validate the time range or state it as a precondition in a note")
    r3 = "block" in text or "r3" in text
    record("SQ7", "PASS" if r3 else "FAIL",
           "R3 (blocked room) is visible" if r3
           else "R3 is invisible - where is the blocked-room check? a message, a guard or a note")
    return sq


# ----------------------------------------------------------------------------------------------
# Activity diagram
# ----------------------------------------------------------------------------------------------

def check_activity(path):
    ids = ("AC1", "AC2", "AC3", "AC4", "AC5", "AC6")
    src = read(path)
    if src is None:
        for cid in ids:
            record(cid, "ERROR", "models/activity.puml not found")
        return
    if not has_start_end(src):
        for cid in ids:
            record(cid, "ERROR", "models/activity.puml has no @startuml / @enduml")
        return
    lines, raw = puml_body(src)
    body = [l.strip() for l in lines]
    has_start = any(re.match(r'^start$', l) or l.startswith("(*)") for l in body)
    has_stop = any(re.match(r'^(stop|end|kill|detach)$', l) or "(*)" in l[1:] for l in body)
    record("AC1", "PASS" if has_start and has_stop else "FAIL",
           "initial and final nodes present" if has_start and has_stop
           else "missing %s" % " and ".join(x for x, ok in (("start", has_start), ("stop", has_stop)) if not ok))

    decisions = [(i, l) for i, l in enumerate(body) if re.match(r'^(if|elseif)\s*\(', l)]
    dtext = [norm(l) for i, l in decisions]
    need = {"time range (R1)": ("time", "duration", "start", "future", "range", "r1"),
            "blocked room (R3)": ("block", "r3"),
            "overlap (R2)": ("overlap", "conflict", "free", "availab", "r2")}
    missing = [k for k, words in need.items() if not any(any(w in d for w in words) for d in dtext)]
    record("AC2", "FAIL" if missing else "PASS",
           "no decision checks: " + ", ".join(missing) if missing
           else "separate decisions check R1, R3 and R2 (%d decisions)" % len(decisions))

    unguarded = []
    for i, l in enumerate(body):
        if re.match(r'^(if|elseif)\s*\(', l) and not re.search(r'then\s*\(\s*[^)\s][^)]*\)', l):
            unguarded.append("line %d then" % (i + 1))
        if re.match(r'^else\b', l) and not re.match(r'^else\s*\(\s*[^)\s][^)]*\)', l):
            unguarded.append("line %d else" % (i + 1))
    if not decisions:
        record("AC3", "FAIL", "no decisions at all")
    else:
        record("AC3", "FAIL" if unguarded else "PASS",
               "unlabelled guard(s): " + ", ".join(unguarded) if unguarded else "every branch has a labelled guard")

    forks = [i for i, l in enumerate(body) if re.match(r'^(fork|split)\b', l)]
    record("AC4", "FAIL" if forks else "PASS",
           "parallel fork/split used - the checks are sequential; use branches" if forks
           else "no parallel paths")

    actions = " ".join(l for l in body if l.startswith(":")).lower()
    conf = "confirm" in actions
    rej = "reject" in actions or "refus" in actions or "deny" in actions
    record("AC5", "PASS" if conf and rej else "FAIL",
           "confirmation on success, rejection on failure" if conf and rej
           else "missing action: " + ", ".join(x for x, ok in (("confirmation", conf), ("rejection", rej)) if not ok))

    create_idx = [i for i, l in enumerate(body) if l.startswith(":") and re.search(r"create|save|insert|store|persist|reserve", l, re.I)]
    rule_idx = [i for i, l in decisions if any(any(w in norm(l) for w in ws) for ws in need.values())]
    if not create_idx:
        record("AC6", "FAIL", "no action creates the booking")
    elif rule_idx and create_idx[0] < max(rule_idx):
        record("AC6", "FAIL", "the booking is created before every rule has been checked")
    else:
        record("AC6", "PASS", "creation comes after all rule checks")


# ----------------------------------------------------------------------------------------------
# Worksheet
# ----------------------------------------------------------------------------------------------

def sections(md):
    out = {}
    cur = None
    for line in md.splitlines():
        m = re.match(r'^##\s+(\d+)\.', line)
        if m:
            cur = int(m.group(1))
            out[cur] = []
            continue
        if cur is not None:
            out[cur].append(line)
    return {k: "\n".join(v) for k, v in out.items()}


def table_rows(text):
    rows = []
    for line in text.splitlines():
        s = line.strip()
        if not s.startswith("|"):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if all(re.match(r'^:?-{3,}:?$', c) for c in cells if c):
            continue
        rows.append(cells)
    return rows[1:] if rows else []   # drop header


def filled(row):
    return all(c and not re.search(r"<[^>]*>", c) for c in row)


def check_worksheet(uc, cl, seq_present, act_present):
    md = read("lab-report.md")
    ids = ("LR1", "LR2", "LR3", "LR4", "LR5", "LR6", "LR7", "CS1", "CS2", "CS3")
    if md is None:
        for cid in ids:
            record(cid, "ERROR", "lab-report.md not found")
        return
    sec = sections(md)

    setup = {r[0].lower(): r[1] for r in table_rows(sec.get(1, "")) if len(r) >= 2}
    need = ("name", "ai assistant", "exact model", "behaviour diagram")
    empty = [k for k in need if not setup.get(k) or re.search(r"<[^>]*>", setup.get(k, ""))]
    record("LR1", "FAIL" if empty else "PASS",
           "§1 not filled: " + ", ".join(empty) if empty else "§1 setup filled (tool and model recorded)")

    s2 = sec.get(2, "")
    blocks = re.findall(r"```[a-z]*\n(.*?)```", s2, re.S)
    real = [b for b in blocks if b.strip() and not re.search(r"<[^>]*>", b)]
    record("LR2", "PASS" if len(real) >= 4 else "FAIL",
           "%d prompts pasted in §2" % len(real) if len(real) >= 4
           else "§2 needs the task 1, 2, 3 and critique prompts pasted (found %d)" % len(real))

    r3 = [r for r in table_rows(sec.get(3, "")) if filled(r)]
    record("LR3", "PASS" if len(r3) >= 2 else "FAIL",
           "%d use-case findings in §3" % len(r3) if len(r3) >= 2 else "§3 needs at least 2 filled findings (found %d)" % len(r3))

    s4 = sec.get(4, "")
    rel_rows = [r for r in table_rows(s4.split("### 4.2")[0]) if filled(r)]
    assum = re.findall(r"^\s*-\s*A\d+\s*:\s*(.+)$", s4, re.M)
    assum = [a for a in assum if not re.search(r"<[^>]*>", a)]
    probs = []
    if len(rel_rows) < 2:
        probs.append("§4.1 needs every association read both ways (found %d rows)" % len(rel_rows))
    if not assum:
        probs.append("§4.3 declares no assumption")
    record("LR4", "FAIL" if probs else "PASS",
           "; ".join(probs) if probs else "§4 relationships read both ways, %d assumption(s) declared" % len(assum))

    s5 = sec.get(5, "")
    r5 = [r for r in table_rows(s5) if filled(r)]
    record("LR5", "PASS" if r5 else "FAIL",
           "%d behaviour-diagram findings in §5" % len(r5) if r5 else "§5 needs at least 1 filled finding")

    r6 = [r for r in table_rows(sec.get(6, "")) if filled(r)]
    verdicts = [r for r in r6 if len(r) >= 4 and re.search(r"accept|reject", r[3], re.I)]
    record("LR6", "PASS" if len(verdicts) >= 3 else "FAIL",
           "%d critique issues with a verdict" % len(verdicts) if len(verdicts) >= 3
           else "§6 needs at least 3 critique rows with accept / reject (found %d)" % len(verdicts))

    r8 = [r for r in table_rows(sec.get(8, "")) if filled(r)]
    diagrams = " ".join(r[1].lower() for r in r8 if len(r) > 1)
    miss = [d for d, ws in (("use case", ("use",)), ("class", ("class",)),
                            ("behaviour", ("seq", "activ", "behav"))) if not any(w in diagrams for w in ws)]
    ok = len(r8) >= 3 and not miss
    record("LR7", "PASS" if ok else "FAIL",
           "%d change-log rows covering all three diagrams" % len(r8) if ok
           else "§8 needs >= 3 rows and one per diagram (rows: %d, missing: %s)" % (len(r8), ", ".join(miss) or "-"))

    # consistency
    stories = read(os.path.join("models", "approved-stories.md"))
    story_ids = set(re.findall(r"\bUS-\d+\b", stories or ""))
    if stories is None:
        record("CS1", "ERROR", "models/approved-stories.md not found")
    else:
        record("CS1", "PASS" if story_ids else "FAIL",
               "%d approved stories" % len(story_ids) if story_ids else "no story IDs (US-01 ...) in approved-stories.md")

    r7 = [r for r in table_rows(sec.get(7, "")) if filled(r)]
    firsts = [norm(r[0]) for r in r7]
    miss_r = [r for r in ("r1", "r2", "r3", "r4") if not any(f.startswith(r) for f in firsts)]
    record("CS2", "FAIL" if miss_r else "PASS",
           "§7 has no filled row for: " + ", ".join(x.upper() for x in miss_r) if miss_r
           else "§7 traces R1-R4 into the diagrams")

    if uc is None:
        record("CS3", "ERROR", "use-case diagram missing, cannot trace")
    elif stories is None:
        record("CS3", "ERROR", "approved-stories.md missing, cannot trace")
    else:
        untraced = []
        for name in uc_display_names(uc):
            hit = False
            for r in r7:
                if len(r) >= 2 and norm(r[1]) == norm(name):
                    ids_in = set(re.findall(r"\bUS-\d+\b", r[0]))
                    if ids_in and ids_in <= story_ids:
                        hit = True
            if not hit:
                untraced.append(name)
        record("CS3", "FAIL" if untraced else "PASS",
               "use case(s) with no §7 row tracing to an approved story: " + ", ".join(untraced) if untraced
               else "every use case traces to an approved story")

    if seq_present and cl is not None:
        sq = parse_sequence(read(os.path.join("models", "sequence.puml")) or "")
        cls = {norm(c) for c in cl["classes"]}
        extra = []
        for d in set(sq["participants"].values()):
            base = d.split(":")[-1].strip()
            if norm(base) not in cls and norm(base) not in ("student", "administrator"):
                extra.append(base)
        unexplained = [e for e in extra if norm(e) not in norm(s5)]
        record("CS4", "FAIL" if unexplained else "PASS",
               "lifeline(s) neither in the class diagram nor explained in §5: " + ", ".join(sorted(unexplained))
               if unexplained else "every lifeline is a domain class or an explained design component")


# ----------------------------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Structural checks over week-04/models/ and lab-report.md")
    parser.add_argument("--json", action="store_true", help="machine-readable output for the grading pipeline")
    args = parser.parse_args()

    if not (os.path.isdir("models") and os.path.isdir("tests")):
        if args.json:
            print(json.dumps({"ok": False, "reason": "wrong-directory"}))
        else:
            print("Run this from inside your week-04 folder:\n")
            print("    cd week-04")
            print("    python tests/check_models.py")
        return 2

    uc = check_usecase(os.path.join("models", "use-case.puml"),
                       os.path.join("models", "original", "use-case.puml"))
    cl = check_class(os.path.join("models", "class.puml"))

    seq_present = os.path.isfile(os.path.join("models", "sequence.puml"))
    act_present = os.path.isfile(os.path.join("models", "activity.puml"))
    if not seq_present and not act_present:
        record("BH0", "ERROR", "no behaviour diagram - add models/sequence.puml OR models/activity.puml")
    if seq_present:
        check_sequence(os.path.join("models", "sequence.puml"))
    if act_present:
        check_activity(os.path.join("models", "activity.puml"))

    # originals and images for every revised diagram present
    missing_orig, missing_img = [], []
    stems = ["use-case", "class"] + (["sequence"] if seq_present else []) + (["activity"] if act_present else [])
    imgs = os.listdir(os.path.join("models", "img")) if os.path.isdir(os.path.join("models", "img")) else []
    for stem in stems:
        if not os.path.isfile(os.path.join("models", stem + ".puml")):
            continue
        if not os.path.isfile(os.path.join("models", "original", stem + ".puml")):
            missing_orig.append("original/%s.puml" % stem)
        if not any(f.startswith(stem + ".") and f.lower().endswith((".png", ".svg")) for f in imgs):
            missing_img.append("img/%s.png|svg" % stem)
    if not any(os.path.isfile(os.path.join("models", st + ".puml")) for st in stems):
        record("FI1", "ERROR", "no diagrams in models/ yet")
        record("FI2", "ERROR", "no diagrams in models/ yet")
    else:
        record("FI1", "FAIL" if missing_orig else "PASS",
               "missing: " + ", ".join(missing_orig) if missing_orig else "the AI's original output is kept for every diagram")
        record("FI2", "FAIL" if missing_img else "PASS",
               "missing rendered image: " + ", ".join(missing_img) if missing_img else "a rendered image for every diagram")

    check_worksheet(uc, cl, seq_present, act_present)

    counts = {v: sum(1 for _, x, _ in RESULTS if x == v) for v in ("PASS", "FAIL", "ERROR")}
    ok = counts["FAIL"] == 0 and counts["ERROR"] == 0
    if args.json:
        rows = [{"id": cid, "title": TITLES.get(cid, cid), "verdict": v, "message": m} for cid, v, m in RESULTS]
        print(json.dumps({"ok": ok, "counts": counts, "rows": rows,
                          "behaviour_diagram": "both" if seq_present and act_present else
                          "sequence" if seq_present else "activity" if act_present else "none"},
                         ensure_ascii=False, indent=2))
        return 0 if ok else 1

    print("Week 04 structural check - shape only, never quality\n")
    for cid, verdict, msg in RESULTS:
        print("%-4s %-5s %s" % (cid, verdict, msg))
    if seq_present and act_present:
        print("\nBoth behaviour diagrams present - the optional extension; both were checked.")
    print("\nSUMMARY pass=%d fail=%d error=%d" % (counts["PASS"], counts["FAIL"], counts["ERROR"]))
    print("A FAIL you report and explain in lab-report.md §9 costs you nothing. One you hide costs the criterion.")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
