#!/usr/bin/env python3
"""
validate_submission.py — checks the shape of week-04/submission.yml.   DO NOT EDIT THIS FILE.

    python tests/validate_submission.py                # from inside week-04/
    python tests/validate_submission.py --json         # machine-readable, for the grading pipeline
    python tests/validate_submission.py --file path/to/submission.yml

It checks SHAPE, never QUALITY. A green run means the file can be read and graded,
not that the work is good.

Verdicts, same vocabulary as check_models.py:
    PASS   the field is present and well-formed
    FAIL   the field is present but wrong
    ERROR  the file is missing, unreadable, or the field is absent entirely

The number of checks is not hardcoded: this file runs `tests/check_models.py --json` and
learns it, so the declaration can never drift away from the checker it reports on.

Exit codes: 0 = no FAIL and no ERROR · 1 = at least one FAIL or ERROR · 2 = file
missing or unparseable · 3 = wrong working directory.

Standard library only. No YAML package: this file understands the restricted subset of
YAML that submission.yml uses, and refuses anything else with a line number.
"""

import argparse
import json
import os
import re
import subprocess
import sys

STUDENT_ID = re.compile(r"^\d{2}[A-Za-z]\d{6}$")
GITHUB_LOGIN = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9]|-(?=[A-Za-z0-9])){0,38}$")
SHORT_SHA = re.compile(r"^[0-9a-fA-F]{7,40}$")
HAS_VERSION = re.compile(r"[0-9]")
CHECK_ID = re.compile(r"^(?:UC|CL|SQ|AC|FI|LR|CS|BH)\d$")
PLACEHOLDER = re.compile(
    r"(^<.*>$)|(\bTODO\b)|(\bFIXME\b)|(\byour name\b)|(\bfill in\b)|(^\.\.\.$)", re.IGNORECASE)
BARE_TOOL_NAMES = {
    "chatgpt", "gpt", "claude", "gemini", "copilot", "github copilot",
    "deepseek", "grok", "mistral", "llama", "qwen", "perplexity", "cursor",
}
YES_NO = {"yes", "no"}
BEHAVIOUR = {"sequence", "activity", "both"}
STORIES_SOURCE = {"week-03", "reference"}
OVERLAP = {"allowed", "not-allowed"}
BLOCKING = {"keep-bookings", "cancel-bookings"}
RULES = {"R1", "R2", "R3", "R4"}
MIN_USE_CASES, MIN_CHANGE_LOG, MIN_FINDINGS, MIN_FINDING_LEN = 5, 3, 3, 25


# --------------------------------------------------------------------------- parsing


class ParseError(Exception):
    pass


def _scalar(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        return [x.strip().strip("\"'") for x in inner.split(",") if x.strip()] if inner else []
    return value


def _strip_comment(raw):
    out, quote = [], None
    for ch in raw:
        if quote:
            if ch == quote:
                quote = None
        elif ch in "\"'":
            quote = ch
        elif ch == "#":
            break
        out.append(ch)
    return "".join(out).rstrip()


def parse_restricted_yaml(text):
    """key: value at column 0; a key with a two-space block of `sub: value` or `- item`
    lines under it; `key: []`. Tabs refused. Anything else is a ParseError with a line number."""
    root, current_key, current_kind = {}, None, None
    for n, raw in enumerate(text.splitlines(), start=1):
        if "\t" in raw:
            raise ParseError(f"line {n}: tab character — use spaces, two per level")
        line = _strip_comment(raw)
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip(" "))
        body = line.strip()
        if indent == 0:
            if body.startswith("-"):
                raise ParseError(f"line {n}: list item at column 0, outside any key")
            if ":" not in body:
                raise ParseError(f"line {n}: expected `key:` or `key: value`, got {body!r}")
            key, _, value = body.partition(":")
            key, value = key.strip(), value.strip()
            if key in root:
                raise ParseError(f"line {n}: duplicate key {key!r}")
            if value == "":
                root[key], current_key, current_kind = None, key, None
            else:
                root[key], current_key, current_kind = _scalar(value), None, None
            continue
        if current_key is None:
            raise ParseError(f"line {n}: indented line does not belong to any key")
        if indent != 2:
            raise ParseError(f"line {n}: indent is {indent}, expected exactly 2")
        if body.startswith("-"):
            item = body[1:].strip()
            if current_kind is None:
                root[current_key], current_kind = [], "list"
            elif current_kind != "list":
                raise ParseError(f"line {n}: list item inside a block of `key: value` lines")
            root[current_key].append(_scalar(item) if item else None)
        else:
            if ":" not in body:
                raise ParseError(f"line {n}: expected `key: value`, got {body!r}")
            key, _, value = body.partition(":")
            key, value = key.strip(), value.strip()
            if current_kind is None:
                root[current_key], current_kind = {}, "map"
            elif current_kind != "map":
                raise ParseError(f"line {n}: `key: value` inside a list block")
            if key in root[current_key]:
                raise ParseError(f"line {n}: duplicate key {key!r}")
            root[current_key][key] = _scalar(value) if value else None
    return root


def get(doc, path):
    node = doc
    for part in path.split("."):
        if not isinstance(node, dict) or part not in node:
            return None
        node = node[part]
    return node


def exists(doc, path):
    node = doc
    for part in path.split("."):
        if not isinstance(node, dict) or part not in node:
            return False
        node = node[part]
    return True


def missing(value):
    return value is None or (isinstance(value, str) and (not value.strip() or PLACEHOLDER.search(value.strip())))


def as_int(value):
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return None


# --------------------------------------------------------------------------- report


class Report:
    def __init__(self):
        self.rows = []

    def add(self, field, verdict, message):
        self.rows.append({"id": field, "title": field, "verdict": verdict, "message": message})

    def ok(self, field, message):
        self.add(field, "PASS", message)

    def fail(self, field, message):
        self.add(field, "FAIL", message)

    def error(self, field, message):
        self.add(field, "ERROR", message)

    def counts(self):
        c = {"PASS": 0, "FAIL": 0, "ERROR": 0}
        for r in self.rows:
            c[r["verdict"]] += 1
        return c

    def clean(self):
        c = self.counts()
        return c["FAIL"] == 0 and c["ERROR"] == 0


def require_text(rep, doc, path, extra=None):
    if not exists(doc, path):
        rep.error(path, "field is absent from the file")
        return
    value = get(doc, path)
    if missing(value):
        rep.fail(path, "left empty or still a placeholder")
        return
    problem = extra(value) if extra else None
    if problem:
        rep.fail(path, problem)
    else:
        rep.ok(path, str(value))


def require_enum(rep, doc, path, allowed):
    if not exists(doc, path):
        rep.error(path, "field is absent from the file")
    elif get(doc, path) not in allowed:
        rep.fail(path, "must be one of %s, got %r" % (" | ".join(sorted(allowed)), get(doc, path)))
    else:
        rep.ok(path, str(get(doc, path)))


# --------------------------------------------------------------------------- context from the folder


def run_checker():
    """Run the week's checker and return its JSON, or None if it cannot be read."""
    try:
        proc = subprocess.run([sys.executable, os.path.join("tests", "check_models.py"), "--json"],
                              capture_output=True, text=True, timeout=60)
        return json.loads(proc.stdout)
    except (OSError, subprocess.TimeoutExpired, json.JSONDecodeError):
        return None


def element_names():
    """Names a finding can point at: classes, use cases, lifelines, actors, from the student's own files."""
    names = set()
    for name in ("use-case", "class", "sequence", "activity"):
        path = os.path.join("models", name + ".puml")
        try:
            with open(path, encoding="utf-8") as fh:
                text = fh.read()
        except OSError:
            continue
        names.update(re.findall(r'"([^"]{3,})"', text))
        names.update(re.findall(r"\(([^)]{3,})\)", text))
        names.update(re.findall(r"\b(?:class|actor|participant|usecase|entity|enum)\s+([A-Za-z_]\w{2,})", text))
    return {n.strip().lower() for n in names if n.strip()}


# --------------------------------------------------------------------------- the checks


def validate(doc):
    rep = Report()

    if as_int(get(doc, "schema")) != 1:
        rep.fail("schema", "must be 1 — do not edit this line")
    else:
        rep.ok("schema", "1")
    if str(get(doc, "week")) != "04":
        rep.fail("week", "must be \"04\", got %r" % get(doc, "week"))
    else:
        rep.ok("week", "04")

    require_text(rep, doc, "student.name")
    require_text(rep, doc, "student.student_id",
                 lambda v: None if STUDENT_ID.match(str(v)) else
                 "does not look like a KBTU student ID (expected e.g. 24B031016), got %r" % v)
    require_text(rep, doc, "student.github",
                 lambda v: None if GITHUB_LOGIN.match(str(v)) else
                 "not a GitHub username — give the username only, not a URL: %r" % v)

    require_text(rep, doc, "assistant.tool")
    require_text(rep, doc, "assistant.model",
                 lambda v: "a tool name is not a model name — give the exact model with its version"
                 if str(v).strip().lower() in BARE_TOOL_NAMES or not HAS_VERSION.search(str(v)) else None)

    checker = run_checker()
    actual_behaviour = (checker or {}).get("behaviour_diagram")
    if not exists(doc, "counts.behaviour_diagram"):
        rep.error("counts.behaviour_diagram", "field is absent from the file")
    elif get(doc, "counts.behaviour_diagram") not in BEHAVIOUR:
        rep.fail("counts.behaviour_diagram", "must be sequence | activity | both")
    elif actual_behaviour and get(doc, "counts.behaviour_diagram") != actual_behaviour:
        rep.fail("counts.behaviour_diagram", "declared %s, but models/ holds %s"
                 % (get(doc, "counts.behaviour_diagram"), actual_behaviour))
    else:
        rep.ok("counts.behaviour_diagram", get(doc, "counts.behaviour_diagram"))
    require_enum(rep, doc, "counts.stories_source", STORIES_SOURCE)
    for path, minimum in (("counts.use_cases", MIN_USE_CASES), ("counts.change_log_rows", MIN_CHANGE_LOG)):
        value = as_int(get(doc, path))
        if not exists(doc, path):
            rep.error(path, "field is absent from the file")
        elif value is None:
            rep.fail(path, "left empty or not a number")
        elif value < minimum:
            rep.fail(path, "the task needs at least %d, you declared %d" % (minimum, value))
        else:
            rep.ok(path, str(value))

    nums = {}
    for name in ("pass", "fail", "error"):
        path = "checker." + name
        value = as_int(get(doc, path))
        if not exists(doc, path):
            rep.error(path, "field is absent from the file")
        elif value is None or value < 0:
            rep.fail(path, "left empty or not a number — copy it from your last checker run")
        else:
            nums[name] = value
            rep.ok(path, str(value))
    if checker is None or "counts" not in checker:
        rep.error("checker.total", "could not run tests/check_models.py --json to learn the number of checks")
    elif len(nums) == 3:
        total = sum(checker["counts"].values())
        if sum(nums.values()) != total:
            rep.fail("checker.total", "pass + fail + error = %d, but check_models.py runs %d checks here"
                     % (sum(nums.values()), total))
        else:
            rep.ok("checker.total", "%d checks, as check_models.py runs" % total)
    else:
        rep.fail("checker.total", "cannot add up — pass, fail and error must all be numbers")
    require_text(rep, doc, "checker.commit",
                 lambda v: None if SHORT_SHA.match(str(v)) else
                 "not a commit hash — use git rev-parse --short HEAD, not a branch name: %r" % v)

    kept = get(doc, "checker.kept_fails")
    if not exists(doc, "checker.kept_fails"):
        rep.error("checker.kept_fails", "field is absent — write [] if you keep no FAIL")
    elif not isinstance(kept, list):
        rep.fail("checker.kept_fails", "must be a list, e.g. [CL5] or []")
    elif any(not CHECK_ID.match(str(k)) for k in kept):
        rep.fail("checker.kept_fails", "must hold check IDs like CL5, got %r" % kept)
    elif "fail" in nums and len(kept) != nums["fail"]:
        rep.fail("checker.kept_fails", "you declare %d FAIL(s) but list %d — list every FAIL you keep"
                 % (nums["fail"], len(kept)))
    else:
        rep.ok("checker.kept_fails", "%d listed" % len(kept))

    require_enum(rep, doc, "assumptions.overlap_touching_bookings", OVERLAP)
    require_enum(rep, doc, "assumptions.blocking_a_booked_room", BLOCKING)

    for path in ("traceability.use_cases_not_traced", "traceability.rules_not_shown"):
        value = get(doc, path)
        if not exists(doc, path):
            rep.error(path, "field is absent from the file")
        elif not isinstance(value, list):
            rep.fail(path, "must be a list — [] is allowed")
        elif path.endswith("rules_not_shown") and any(v not in RULES for v in value):
            rep.fail(path, "may only hold R1, R2, R3, R4")
        else:
            rep.ok(path, "[%s]" % ", ".join(str(v) for v in value))

    findings = get(doc, "review_findings")
    if not exists(doc, "review_findings"):
        rep.error("review_findings", "field is absent from the file")
    else:
        items = [f for f in (findings if isinstance(findings, list) else [])
                 if isinstance(f, str) and f.strip() and not PLACEHOLDER.search(f)]
        names = element_names()
        vague = [f for f in items if len(f) < MIN_FINDING_LEN or not (
            re.search(r"\b(?:R[1-4]|US-\d{2})\b", f) or any(n in f.lower() for n in names))]
        if len(items) < MIN_FINDINGS:
            rep.fail("review_findings", "needs %d or more lines, found %d" % (MIN_FINDINGS, len(items)))
        elif vague:
            rep.fail("review_findings", "%d finding(s) name no element of your diagrams, no rule and no story: %r"
                     % (len(vague), vague[0][:60]))
        else:
            rep.ok("review_findings", "%d findings, each naming an element" % len(items))

    for path in ("honesty.originals_unedited", "honesty.can_explain_everything_submitted",
                 "honesty.ai_usage_disclosed"):
        require_enum(rep, doc, path, YES_NO)
    return rep


# --------------------------------------------------------------------------- output


def print_human(rep, path):
    print("Week 04 submission.yml — shape only, never quality   (%s)\n" % path)
    width = max(len(r["id"]) for r in rep.rows)
    for r in rep.rows:
        print("%-6s %-*s  %s" % (r["verdict"], width, r["id"], r["message"]))
    c = rep.counts()
    print("-" * 72)
    print("%d PASS · %d FAIL · %d ERROR   (%d fields)" % (c["PASS"], c["FAIL"], c["ERROR"], len(rep.rows)))
    print("SUMMARY pass=%d fail=%d error=%d" % (c["PASS"], c["FAIL"], c["ERROR"]))
    if rep.clean():
        print("The declaration can be read and graded. Your checker numbers are re-run at the commit you name.")


def main():
    parser = argparse.ArgumentParser(description="Validate week-04/submission.yml")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--file", default="submission.yml")
    args = parser.parse_args()

    if not (os.path.isdir("models") and os.path.isdir("tests")):
        if args.json:
            print(json.dumps({"ok": False, "reason": "wrong-directory"}))
        else:
            print("Run this from inside your week-04 folder:\n\n    cd week-04\n    python tests/validate_submission.py")
        return 3
    try:
        with open(args.file, encoding="utf-8") as fh:
            doc = parse_restricted_yaml(fh.read())
    except OSError:
        reason = "%s not found" % args.file
        print(json.dumps({"ok": False, "reason": reason}) if args.json else "ERROR  " + reason)
        return 2
    except (ParseError, UnicodeDecodeError) as exc:
        reason = "%s could not be read: %s" % (args.file, exc)
        print(json.dumps({"ok": False, "reason": reason}) if args.json else "ERROR  " + reason)
        return 2

    rep = validate(doc)
    if args.json:
        print(json.dumps({
            "ok": rep.clean(),
            "counts": rep.counts(),
            "rows": rep.rows,
            "declared": {
                "student_id": get(doc, "student.student_id"),
                "github": get(doc, "student.github"),
                "tool": get(doc, "assistant.tool"),
                "model": get(doc, "assistant.model"),
                "commit": get(doc, "checker.commit"),
                "checker": {"pass": as_int(get(doc, "checker.pass")),
                            "fail": as_int(get(doc, "checker.fail")),
                            "error": as_int(get(doc, "checker.error"))},
                "kept_fails": get(doc, "checker.kept_fails"),
                "behaviour_diagram": get(doc, "counts.behaviour_diagram"),
                "assumptions": get(doc, "assumptions"),
                "traceability": get(doc, "traceability"),
                "findings": get(doc, "review_findings"),
            },
        }, ensure_ascii=False, indent=2))
    else:
        print_human(rep, args.file)
    return 0 if rep.clean() else 1


if __name__ == "__main__":
    sys.exit(main())
